# Generated by Django 3.0.6 on 2020-05-27 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lister.Client', to_field='nom')),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lister.Type', to_field='nom')),
            ],
        ),
    ]
