# Generated by Django 3.0.6 on 2020-05-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='hostname',
            field=models.CharField(default='topensi srv', max_length=100),
            preserve_default=False,
        ),
    ]
